# Accept namespaces as args. This requires tilt > v0.22.7

config.define_string_list("namespaces")
cfg = config.parse()

namespaces = cfg.get('namespaces', [])
is_windows = True if os.name == "nt" else False
tiltdir=os.path.dirname(__file__ )

if (is_windows):
  trigger_file = str(local('powershell -nop -c New-TemporaryFile', quiet=True, echo_off=True)).strip()
else:
  trigger_file = str(local('mktemp "${TMPDIR:-/tmp}/tilt-kubefwd.XXXXXXXXX"')).strip()

# Creates a button that refreshes the kubefwd without
# requiring new credentials.
local(
  command=['./create-refresh-button.sh', trigger_file],
  command_bat=['powershell', '-nop', '-File', '%s\\create-refresh-button.ps1' % tiltdir, '-Trigger', trigger_file]
)

local_resource(
  name='kubefwd:run',
  serve_cmd=['./sudo-kubefwd.sh', trigger_file],
  serve_cmd_bat=['sudo-kubefwd.bat', trigger_file],
  deps=['sudo-kubefwd.sh', 'run-kubefwd.sh', 'run-kubefwd-internal.sh', 'watch-namespaces.sh'],
  serve_env={'TILT_CFG_NAMESPACES': ' '.join(namespaces)})
